---
- hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - vars/main.yml

  tasks:
    - copy: src=xcode-cli-tools.sh dest=/tmp/xcode-cli-tools.sh mode=644
    - command: sudo bash /tmp/xcode-cli-tools.sh

  roles:
    - homebrew

  tasks:
    - name: Install gems
      gem: name="{{ item }}" state=latest
      with_items:
        - aws-keychain-util

  tasks:
    - include: tasks/dotfiles.yml
    - include: tasks/preferences.yml


