---
- hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - homebrew

  tasks:
    - name: Install gems
      gem: name="{{ item }}" state=latest
      with_items:
        - aws-keychain-util

  tasks:
    - include: tasks/dotfiles.yml
    - include: tasks/preferences.yml


