---
- hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - vars/main.yml

  roles:
    - homebrew

  tasks:
    - include: tasks/preferences.yml
    - include: tasks/dotfiles.yml
